import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'vi' | 'en';

export const translations = {
  vi: {
    // Header / Navigation
    appTitle: 'STAT-ALERT',
    appSubTitle: 'Hệ Thống Cảnh Báo Khẩn Cấp Bệnh Viện & Telemetry Sinh Tồn',
    icuCall: 'ICU Call',
    statusOnline: 'Hệ Thống Trực Tuyến',
    statusReconnecting: 'Đang kết nối lại...',
    tabDoctor: 'Bác Sĩ Trực',
    tabNurse: 'Trạm Y Tá',
    tabMedicationCalendar: 'Lịch Thuốc & Google Calendar',
    tabSimulator: 'Giả Lập Máy Đo',
    tabAudit: 'Lịch Sử & Audit',
    tabStaffAdmin: 'Quản Lý Nhân Sự',
    tabSettings: 'Cài Đặt Hệ Thống',
    soundOn: 'Âm thanh cảnh báo: BẬT',
    soundOff: 'Âm thanh cảnh báo: TẮT',
    testSound: 'Test Chuông',
    enableNotifications: 'Bật Thông Báo Desktop',
    notificationsEnabled: 'Thông Báo Màn Hình Đã Bật',
    dutyDoctor: 'Bác sĩ:',
    onDutyTag: '(Đang trực)',
    backupTag: '(Dự phòng)',
    resetDataTooltip: 'Reset dữ liệu mẫu',

    // Theme & Settings Tabs
    settingsTitle: 'Cài Đặt Hệ Thống & Cấu Hình',
    tabGeneralSettings: 'Giao Diện & Ngôn Ngữ',
    tabThresholdSettings: 'Cấu Hình Ngưỡng & Leo Thang',
    tabPersonnelAdmin: 'Quản Lý Nhân Sự Y Tế',
    themeMode: 'Chế độ giao diện hiển thị:',
    themeDark: 'Giao Diện Tối (Dark ICU Monitor)',
    themeLight: 'Giao Diện Sáng (Light Clinical)',
    languageTitle: 'Ngôn ngữ hiển thị (Language):',
    langVietnamese: 'Tiếng Việt (Vietnamese)',
    langEnglish: 'Tiếng Anh (English)',

    // Personnel Admin
    adminTitle: 'Trang Admin Quản Lý Nhân Sự & Phân Ca Trực',
    adminSubtitle: 'Quản lý danh sách bác sĩ, điều dưỡng, phân bổ ca trực 24/7 và hotline liên lạc khẩn cấp',
    btnAddStaff: 'Thêm Bác Sĩ / Nhân Viên',
    btnEditStaff: 'Chỉnh Sửa',
    btnDeleteStaff: 'Xóa',
    staffListHeader: 'Danh Sách Đội Ngũ Y Bác Sĩ & Điều Dưỡng',
    staffName: 'Họ và tên:',
    staffRole: 'Chức danh / Vị trí:',
    staffDepartment: 'Khoa / Phòng ban:',
    staffPhone: 'Số điện thoại trực:',
    staffEmail: 'Email liên hệ:',
    staffShift: 'Ca trực quy định:',
    staffStatus: 'Trạng thái ca trực:',
    staffOnCallStatus: 'Trực chính (On-Call)',
    staffBackupStatus: 'Dự phòng (Backup)',
    staffOffDutyStatus: 'Nghỉ ca',
    btnSaveStaff: 'Lưu Thông Tin Nhân Viên',
    btnSavingStaff: 'Đang lưu...',
    editStaffModalTitle: 'Chỉnh Sửa Thông Tin Nhân Viên Y Tế',
    addStaffModalTitle: 'Thêm Bác Sĩ / Điều Dưỡng Mới',
    confirmDeleteStaff: 'Bạn có chắc chắn muốn xóa nhân viên này khỏi hệ thống phân ca trực?',
    cannotDeleteLastStaff: 'Phải duy trì ít nhất 1 nhân viên y tế trong danh sách trực.',

    // Doctor Portal
    doctorOnDuty: 'Bác Sĩ Trực Ca',
    hotline: 'Hotline trực:',
    dutyStatus: 'Trạng thái ca trực:',
    statusOnCall: 'ĐANG TRỰC CHÍNH (ON-CALL)',
    statusOffDuty: 'NGHỈ TRỰC / DỰ PHÒNG',
    btnSwitchBackup: 'Đổi sang Dự phòng',
    btnSwitchOnCall: 'Bật Trực Chính',
    activeAlertsPending: 'CẢNH BÁO KHẨN CẤP ĐANG CHỜ TIẾP NHẬN',
    broadcastingAlert: 'Đang phát tín hiệu chuông và thông báo đến bác sĩ trực...',
    codeRed: 'BÁO ĐỘNG ĐỎ (CODE RED)',
    criticalAlert: 'CẢNH BÁO NGUY CẤP',
    warningAlert: 'CẢNH BÁO',
    room: 'Phòng',
    patientCode: 'Mã BN:',
    measuredHR: 'Nhịp Tim Đo Được',
    autoEscalateIn: 'Tự động chuyển BS dự phòng sau:',
    escalatedToBackup: 'Đã leo thang chuyển BS Dự Phòng!',
    btnAcknowledgeNow: 'TIẾP NHẬN CẢNH BÁO NGAY',
    btnAcknowledging: 'Đang xử lý...',
    patientListHeader: 'Danh Sách Bệnh Nhân Theo Dõi ICU',
    patientCount: 'bệnh nhân',
    noPatients: 'Không có bệnh nhân',
    stableStatus: 'Ổn Định',
    warningStatus: 'Cần Lưu Ý',
    criticalStatus: 'Nguy Cấp',
    lastRecordedHR: 'Nhịp tim gần nhất:',
    diagnosis: 'Chẩn đoán:',
    emergencyTestTriggers: 'Thử nghiệm khẩn cấp:',
    triggerVfib: 'Bắn Rung Thất (172 BPM)',
    triggerBrady: 'Bắn Ngừng Tim (34 BPM)',
    acknowledgedAlertsHeader: 'Cảnh Báo Đã Tiếp Nhận - Đang Chờ Bác Sĩ Hoàn Tất Xử Lý',
    acknowledgedBy: 'Tiếp nhận bởi:',
    responseTime: 'Thời gian phản hồi:',
    btnResolveComplete: 'Bác Sĩ Xác Nhận Hoàn Tất Xử Lý',
    btnResolving: 'Đang lưu...',
    clinicalNotesPlaceholder: 'Nhập ghi chú lâm sàng / kết quả xử lý tại giường...',
    btnSubmitResolution: 'Lưu & Đóng Cảnh Báo',
    btnCancel: 'Hủy',

    // Nurse Station Kiosk
    kioskTitle: 'Màn Hình Trạm Y Tá Trung Tâm',
    kioskSubtitle: 'Chế độ giám sát liên tục 24/7 • Tự động kích hoạt còi báo động & đèn chớp khi có sự cố',
    btnFullscreen: 'Toàn Màn Hình (Kiosk)',
    btnExitFullscreen: 'Thu Nhỏ',
    emergencyRoomActive: 'SỰ CỐ KHẨN CẤP ĐANG BÁO ĐỘNG TẠI PHÒNG BỆNH',
    sirenActiveNotice: 'Còi báo động đang kêu tại trạm y tá',
    kioskHeartRate: 'Nhịp Tim Telemetry',
    btnNurseAcknowledge: 'ĐÃ TIẾP NHẬN TẠI TRẠM (TẮT CÒI)',
    bedMapTitle: 'Sơ Đồ Giường Bệnh Trực Quan 24/7',
    bedSafe: 'An Toàn',
    bedAlerting: 'BÁO ĐỘNG',
    testTriggerBed: 'Thử Cảnh Báo',
    activeDoctorOnDuty: 'Bác sĩ trực chính:',
    backupDoctorOnDuty: 'Bác sĩ dự phòng:',

    // Telemetry Simulator
    simPresetsTitle: 'Thử Nghiệm Cảnh Báo 1-Click (Quick Presets)',
    simPresetsDesc: 'Bắn ngay dữ liệu nhịp tim bất thường để kiểm tra chuông cảnh báo, còi trạm y tá và SignalR Hub.',
    presetVfib: 'Rung Thất Nguy Kịch (172 BPM)',
    presetBrady: 'Nguy Cơ Ngừng Tim (34 BPM)',
    presetHypoxia: 'Tụt SpO2 Cấp (78%)',
    presetNormal: 'Nhịp Bình Thường (76 BPM)',
    autoStreamTitle: 'Bộ Tạo Luồng Dữ Liệu Tự Động (Auto-Streamer)',
    autoStreamDesc: 'Tự động gửi dữ liệu nhịp tim liên tục từ các thiết bị đo tới máy chủ.',
    streamFrequency: 'Tần suất gửi:',
    anomalyChance: 'Tỷ lệ bất thường ngẫu nhiên:',
    packetsSent: 'Gói tin đã gửi:',
    btnStartStream: 'Bắt Đầu Luồng Dữ Liệu Tự Động',
    btnStopStream: 'Dừng Luồng Dữ Liệu',
    manualFormTitle: 'Gửi Dữ Liệu Sinh Tồn Thủ Công',
    selectPatient: 'Chọn Bệnh Nhân:',
    heartRateInput: 'Nhịp Tim (BPM):',
    spO2Input: 'Độ Bão Hòa Oxy SpO2 (%):',
    systolicInput: 'Huyết Áp Tâm Thu (mmHg):',
    diastolicInput: 'Huyết Áp Tâm Trương (mmHg):',
    btnSendVital: 'Gửi Dữ Liệu Telemetry',
    liveTelemetryTitle: 'Nhật Ký Tín Hiệu Telemetry Thời Gian Thực',
    noVitalsYet: 'Chưa có tín hiệu đo nào được gửi...',

    // Alert Audit History
    auditTitle: 'Lịch Sử & Kiểm Toán Cảnh Báo (Audit Trail)',
    auditSubtitle: 'Theo dõi toàn bộ chu trình tiếp nhận, thời gian phản hồi và lưu vết xử lý lâm sàng',
    btnExportCsv: 'Xuất Báo Cáo CSV',
    statTotalAlerts: 'Tổng Cảnh Báo',
    statAvgResponseTime: 'Thời Gian Phản Hồi TB',
    statEscalationRate: 'Tỷ Lệ Leo Thang',
    statTotalPackets: 'Tổng Tín Hiệu Telemetry',
    searchPlaceholder: 'Tìm theo tên bệnh nhân, phòng, lý do...',
    filterAllSeverities: 'Tất cả mức độ',
    filterAllStatus: 'Tất cả trạng thái',
    filterPending: 'Đang chờ (Pending)',
    filterAcknowledged: 'Đã tiếp nhận (Acknowledged)',
    filterResolved: 'Đã hoàn tất (Resolved)',
    tableColTime: 'Thời Điểm',
    tableColPatient: 'Bệnh Nhân / Phòng',
    tableColVital: 'Tín Hiệu Sinh Tồn',
    tableColReason: 'Lý Do Báo Động',
    tableColStatus: 'Trạng Thái',
    tableColResponse: 'Phản Hồi',
    tableColActions: 'Hành Động',
    btnViewTimeline: 'Xem Chi Tiết Audit',
    auditModalTitle: 'Chi Tiết Kiểm Toán Chu Trình Cảnh Báo',
    step1Detected: '1. Hệ thống phát hiện bất thường & phát cảnh báo',
    step2Escalated: '2. Tự động leo thang gửi BS Dự phòng',
    step3Acknowledged: '3. Nhân viên tiếp nhận cảnh báo',
    step4Resolved: '4. Bác sĩ hoàn tất xử lý tại giường',
    btnClose: 'Đóng',

    // Settings Modal
    thresholdSettingsTitle: 'Cấu Hình Ngưỡng Cảnh Báo & Escalation',
    critLowHR: 'Nguy kịch Nhịp Chậm (BPM <=):',
    critLowHRDesc: 'Mặc định: 40 BPM (Nguy cơ ngừng tim)',
    critHighHR: 'Nguy kịch Nhịp Nhanh (BPM >=):',
    critHighHRDesc: 'Mặc định: 150 BPM (Rung thất / Cơn nhịp nhanh)',
    minNormalHR: 'Ngưỡng Thấp Nhịp Bình Thường:',
    maxNormalHR: 'Ngưỡng Cao Nhịp Bình Thường:',
    minSpO2: 'Ngưỡng SpO2 Tối Thiểu (%):',
    escalationTimeout: 'Thời Gian Chờ Escalation (Giây):',
    escalationTimeoutDesc: 'Tự động chuyển BS dự phòng sau X giây',
    btnResetDefaultData: 'Reset dữ liệu mẫu ban đầu',
    btnSaveSettings: 'Lưu Thay Đổi',
    btnSaving: 'Đang lưu...',

    // Medication & Google Calendar
    medicationTitle: 'Lịch Tiếp Nhận Thuốc & Đồng Bộ Google Calendar',
    medicationSubtitle: 'Quản lý lịch uống/tiêm/truyền thuốc cho bệnh nhân, tự động cảnh báo giờ dùng và đồng bộ lịch trực tiếp về Google Calendar của Bác sĩ & Y tá',
    btnAddMedication: 'Kê Đơn & Thêm Lịch Thuốc',
    btnSyncAllToGoogleCalendar: 'Đồng Bộ Lịch Thuốc Sang Google Calendar',
    btnConnectGoogleCalendar: 'Đăng Nhập Google Calendar',
    btnDisconnectGoogleCalendar: 'Ngắt Kết Nối',
    googleCalendarConnected: 'Đã Kết Nối Google Calendar',
    googleCalendarNotConnected: 'Chưa Kết Nối Google Calendar (Bấm để kích hoạt đồng bộ tự động)',
    btnAdministerMed: 'Cho Dùng Thuốc & Ký Nhận',
    btnAdministering: 'Đang lưu...',
    btnHoldMed: 'Tạm Hoãn Liều',
    btnSyncSingleToGCal: 'Đồng bộ Google Calendar',
    btnOpenInGCal: 'Mở trên Google Calendar',
    medStatusScheduled: 'Đang Chờ Dùng',
    medStatusAdministered: 'Đã Cho Dùng Thuốc',
    medStatusHeld: 'Tạm Hoãn',
    medStatusMissed: 'Quá Giờ',
    medStatusCancelled: 'Đã Hủy',
    routeOral: 'Uống (Oral)',
    routeIV: 'Tiêm Tĩnh Mạch (IV)',
    routeIM: 'Tiêm Bắp (IM)',
    routeSubcutaneous: 'Tiêm Dưới Da (SC)',
    routeInfusion: 'Truyền Dịch / Bơm Tiêm Điện',
    routeInhalation: 'Khí Dung / Hít',
    routeTopical: 'Bôi Ngoài Da',
    medSelectPatient: 'Chọn Bệnh Nhân:',
    medNameLabel: 'Tên Thuốc & Hàm Lượng:',
    medDosageLabel: 'Liều Lượng Cụ Thể:',
    medRouteLabel: 'Đường Dùng Thuốc:',
    medTimeLabel: 'Khung Giờ Cho Dùng (HH:mm):',
    medFrequencyLabel: 'Tần Suất Sử Dụng:',
    medDoctorLabel: 'Bác Sĩ Chỉ Định / Kê Đơn:',
    medNurseLabel: 'Điều Dưỡng Phụ Trách:',
    medInstructionsLabel: 'Hướng Dẫn & Cảnh Báo Lâm Sàng:',
    medPreVitalsLabel: 'Yêu cầu kiểm tra Mạch/Huyết áp trước khi cho dùng',
    medSearchPlaceholder: 'Tìm theo tên thuốc, bệnh nhân, phòng...',
    medAdministerModalTitle: 'Xác Nhận Đã Cho Bệnh Nhân Dùng Thuốc',
    medHoldModalTitle: 'Ghi Nhận Tạm Hoãn Liều Thuốc',
    medPulseBeforeDose: 'Nhịp tim đo được trước dùng (BPM):',
    medBPBeforeDose: 'Huyết áp đo được (mmHg):',
    medAdministerNotes: 'Ghi chú lâm sàng / Tình trạng bệnh nhân sau dùng:',
    medHoldReason: 'Lý do tạm hoãn (ví dụ: Mạch chậm < 50 bpm, chuẩn bị làm xét nghiệm):',
    medFilterAll: 'Tất cả trạng thái',
    medFilterScheduled: 'Chờ đến giờ',
    medFilterAdministered: 'Đã hoàn tất',
    medFilterHeld: 'Tạm hoãn',
    medTotalDoses: 'Tổng Liều Trong Ngày',
    medCompletedDoses: 'Đã Cho Dùng',
    medPendingDoses: 'Đang Chờ Dùng',
    medSyncedCount: 'Đã Đồng Bộ Lịch Google',

    // Footer
    footerSystemName: 'Hệ Thống Cảnh Báo Khẩn Cấp Bệnh Viện (Stat-Alert) • Bác Sĩ & Trạm Y Tá Trực',
    footerVersion: 'Phiên bản ICU Telemetry 2.4',
  },
  en: {
    // Header / Navigation
    appTitle: 'STAT-ALERT',
    appSubTitle: 'Hospital Emergency Telemetry & Clinical Escalation Alert System',
    icuCall: 'ICU Call',
    statusOnline: 'System Online',
    statusReconnecting: 'Reconnecting...',
    tabDoctor: 'On-Call Doctor',
    tabNurse: 'Nurse Station',
    tabMedicationCalendar: 'Medication & Google Calendar',
    tabSimulator: 'Telemetry Simulator',
    tabAudit: 'Audit & History',
    tabStaffAdmin: 'Personnel Admin',
    tabSettings: 'System Settings',
    soundOn: 'Alert Sound: ON',
    soundOff: 'Alert Sound: OFF',
    testSound: 'Test Chime',
    enableNotifications: 'Enable Desktop Push',
    notificationsEnabled: 'Desktop Push Enabled',
    dutyDoctor: 'Doctor:',
    onDutyTag: '(On-Call)',
    backupTag: '(Backup)',
    resetDataTooltip: 'Reset Sample Data',

    // Theme & Settings Tabs
    settingsTitle: 'System Settings & Configuration',
    tabGeneralSettings: 'Appearance & Language',
    tabThresholdSettings: 'Thresholds & Escalation',
    tabPersonnelAdmin: 'Medical Staff Admin',
    themeMode: 'Display theme mode:',
    themeDark: 'Dark Mode (ICU Clinical Monitor)',
    themeLight: 'Light Mode (Clinical Crisp)',
    languageTitle: 'Display Language:',
    langVietnamese: 'Vietnamese (Tiếng Việt)',
    langEnglish: 'English (English)',

    // Personnel Admin
    adminTitle: 'Staff & On-Duty Shift Administration',
    adminSubtitle: 'Manage hospital doctors, ICU nurses, 24/7 on-call rosters, and emergency hotline routing',
    btnAddStaff: 'Add Doctor / Staff Member',
    btnEditStaff: 'Edit',
    btnDeleteStaff: 'Delete',
    staffListHeader: 'Clinical Physicians & Nursing Roster',
    staffName: 'Full Name:',
    staffRole: 'Role / Designation:',
    staffDepartment: 'Department:',
    staffPhone: 'Duty Hotline / Phone:',
    staffEmail: 'Email address:',
    staffShift: 'Assigned Shift:',
    staffStatus: 'Duty Status:',
    staffOnCallStatus: 'Primary On-Call',
    staffBackupStatus: 'Backup On-Call',
    staffOffDutyStatus: 'Off-Duty',
    btnSaveStaff: 'Save Staff Info',
    btnSavingStaff: 'Saving...',
    editStaffModalTitle: 'Edit Medical Personnel Information',
    addStaffModalTitle: 'Add New Clinical Doctor / Nurse',
    confirmDeleteStaff: 'Are you sure you want to remove this staff member from the clinical duty roster?',
    cannotDeleteLastStaff: 'Must keep at least 1 medical staff member in the active roster.',

    // Doctor Portal
    doctorOnDuty: 'On-Call Doctor Portal',
    hotline: 'Duty Hotline:',
    dutyStatus: 'Duty Status:',
    statusOnCall: 'ACTIVE ON-CALL (PRIMARY)',
    statusOffDuty: 'OFF-DUTY / BACKUP',
    btnSwitchBackup: 'Switch to Backup',
    btnSwitchOnCall: 'Set Primary On-Call',
    activeAlertsPending: 'ACTIVE EMERGENCY ALERTS AWAITING ACKNOWLEDGEMENT',
    broadcastingAlert: 'Broadcasting siren chime and urgent popup to on-call doctor...',
    codeRed: 'CODE RED (FATAL EMERGENCY)',
    criticalAlert: 'CRITICAL ALERT',
    warningAlert: 'WARNING',
    room: 'Room',
    patientCode: 'Patient ID:',
    measuredHR: 'Measured Heart Rate',
    autoEscalateIn: 'Auto-escalate to backup doctor in:',
    escalatedToBackup: 'Escalated to Backup Doctor!',
    btnAcknowledgeNow: 'ACKNOWLEDGE EMERGENCY NOW',
    btnAcknowledging: 'Processing...',
    patientListHeader: 'ICU Monitored Patients List',
    patientCount: 'patients',
    noPatients: 'No patients found',
    stableStatus: 'Stable',
    warningStatus: 'Attention',
    criticalStatus: 'Critical',
    lastRecordedHR: 'Latest heart rate:',
    diagnosis: 'Diagnosis:',
    emergencyTestTriggers: 'Emergency Test Triggers:',
    triggerVfib: 'Simulate V-Fib (172 BPM)',
    triggerBrady: 'Simulate Bradycardia (34 BPM)',
    acknowledgedAlertsHeader: 'Acknowledged Alerts - In Progress (Awaiting Clinical Resolution)',
    acknowledgedBy: 'Acknowledged by:',
    responseTime: 'Response Time:',
    btnResolveComplete: 'Physician Confirm Clinical Resolution',
    btnResolving: 'Saving...',
    clinicalNotesPlaceholder: 'Enter clinical bedside findings and patient resolution notes...',
    btnSubmitResolution: 'Save & Close Alert',
    btnCancel: 'Cancel',

    // Nurse Station Kiosk
    kioskTitle: 'Central Nurse Station Display',
    kioskSubtitle: 'Continuous 24/7 Monitoring Mode • Automatic visual beacon and audio siren triggers',
    btnFullscreen: 'Fullscreen (Kiosk)',
    btnExitFullscreen: 'Exit Fullscreen',
    emergencyRoomActive: 'ACTIVE EMERGENCY ALARM AT PATIENT ROOM',
    sirenActiveNotice: 'Audible siren active at nurse station',
    kioskHeartRate: 'Telemetry Heart Rate',
    btnNurseAcknowledge: 'ACKNOWLEDGE AT STATION (MUTE SIREN)',
    bedMapTitle: '24/7 Visual Bed Telemetry Layout',
    bedSafe: 'Normal',
    bedAlerting: 'ALARM',
    testTriggerBed: 'Test Alarm',
    activeDoctorOnDuty: 'Primary On-Call Doctor:',
    backupDoctorOnDuty: 'Backup Doctor:',

    // Telemetry Simulator
    simPresetsTitle: '1-Click Emergency Test Triggers (Quick Presets)',
    simPresetsDesc: 'Instantly transmit abnormal vital telemetry to verify doctor chime, nurse siren, and SignalR hub.',
    presetVfib: 'Critical Ventricular Fibrillation (172 BPM)',
    presetBrady: 'Imminent Cardiac Arrest (34 BPM)',
    presetHypoxia: 'Acute Hypoxemia (78% SpO2)',
    presetNormal: 'Stable Rhythm (76 BPM)',
    autoStreamTitle: 'Automated Telemetry Streamer',
    autoStreamDesc: 'Continuously stream simulated patient monitor telemetry to the server.',
    streamFrequency: 'Stream Frequency:',
    anomalyChance: 'Random Anomaly Probability:',
    packetsSent: 'Packets Transmitted:',
    btnStartStream: 'Start Telemetry Stream',
    btnStopStream: 'Stop Stream',
    manualFormTitle: 'Manual Telemetry Injection',
    selectPatient: 'Select Patient:',
    heartRateInput: 'Heart Rate (BPM):',
    spO2Input: 'Oxygen Saturation SpO2 (%):',
    systolicInput: 'Systolic BP (mmHg):',
    diastolicInput: 'Diastolic BP (mmHg):',
    btnSendVital: 'Transmit Vital Reading',
    liveTelemetryTitle: 'Live Telemetry Ingestion Log',
    noVitalsYet: 'No vital packets transmitted yet...',

    // Alert Audit History
    auditTitle: 'Alert Audit Trail & Clinical History',
    auditSubtitle: 'Track complete alert lifecycles, response metrics, escalation rates, and bedside doctor resolutions',
    btnExportCsv: 'Export CSV Report',
    statTotalAlerts: 'Total Alerts',
    statAvgResponseTime: 'Avg Response Time',
    statEscalationRate: 'Escalation Rate',
    statTotalPackets: 'Telemetry Packets',
    searchPlaceholder: 'Search by patient name, room, reason...',
    filterAllSeverities: 'All Severities',
    filterAllStatus: 'All Statuses',
    filterPending: 'Pending',
    filterAcknowledged: 'Acknowledged',
    filterResolved: 'Resolved',
    tableColTime: 'Timestamp',
    tableColPatient: 'Patient / Room',
    tableColVital: 'Vitals',
    tableColReason: 'Alarm Reason',
    tableColStatus: 'Status',
    tableColResponse: 'Response',
    tableColActions: 'Actions',
    btnViewTimeline: 'View Audit Trail',
    auditModalTitle: 'Alert Lifecycle Audit Inspection',
    step1Detected: '1. Telemetry anomaly detected & alert triggered',
    step2Escalated: '2. Auto-escalated to backup physician',
    step3Acknowledged: '3. Clinical staff acknowledged alert',
    step4Resolved: '4. Physician concluded bedside treatment',
    btnClose: 'Close',

    // Settings Modal
    thresholdSettingsTitle: 'Alarm Thresholds & Escalation Configuration',
    critLowHR: 'Critical Bradycardia (BPM <=):',
    critLowHRDesc: 'Default: 40 BPM (Risk of cardiac arrest)',
    critHighHR: 'Critical Tachycardia (BPM >=):',
    critHighHRDesc: 'Default: 150 BPM (Ventricular tachycardia/V-Fib)',
    minNormalHR: 'Lower Normal Heart Rate:',
    maxNormalHR: 'Upper Normal Heart Rate:',
    minSpO2: 'Minimum SpO2 Threshold (%):',
    escalationTimeout: 'Escalation Timeout (Seconds):',
    escalationTimeoutDesc: 'Auto-escalate to backup doctor after X seconds',
    btnResetDefaultData: 'Reset Initial Sample Data',
    btnSaveSettings: 'Save Configuration',
    btnSaving: 'Saving...',

    // Medication & Google Calendar
    medicationTitle: 'Patient Medication Schedule & Google Calendar Integration',
    medicationSubtitle: 'Manage hospital medication administration records (MAR), trigger scheduled dose chimes, and sync real-time alerts to Doctor and Nurse Google Calendars',
    btnAddMedication: 'Prescribe & Add Schedule',
    btnSyncAllToGoogleCalendar: 'Sync All Meds to Google Calendar',
    btnConnectGoogleCalendar: 'Connect Google Calendar',
    btnDisconnectGoogleCalendar: 'Disconnect',
    googleCalendarConnected: 'Google Calendar Connected',
    googleCalendarNotConnected: 'Google Calendar Disconnected (Click to enable automatic cloud sync)',
    btnAdministerMed: 'Administer & Sign-Off',
    btnAdministering: 'Saving...',
    btnHoldMed: 'Hold Dose',
    btnSyncSingleToGCal: 'Sync to Google Calendar',
    btnOpenInGCal: 'Open in Google Calendar',
    medStatusScheduled: 'Scheduled / Due',
    medStatusAdministered: 'Administered',
    medStatusHeld: 'Held / Delayed',
    medStatusMissed: 'Missed',
    medStatusCancelled: 'Cancelled',
    routeOral: 'Oral (PO)',
    routeIV: 'Intravenous (IV)',
    routeIM: 'Intramuscular (IM)',
    routeSubcutaneous: 'Subcutaneous (SC)',
    routeInfusion: 'IV Infusion / Syringe Pump',
    routeInhalation: 'Inhalation / Nebulizer',
    routeTopical: 'Topical',
    medSelectPatient: 'Select Patient:',
    medNameLabel: 'Medication Name & Strength:',
    medDosageLabel: 'Prescribed Dosage:',
    medRouteLabel: 'Administration Route:',
    medTimeLabel: 'Scheduled Time (HH:mm):',
    medFrequencyLabel: 'Administration Frequency:',
    medDoctorLabel: 'Prescribing Physician:',
    medNurseLabel: 'Assigned Duty Nurse:',
    medInstructionsLabel: 'Clinical Notes & Administration Warnings:',
    medPreVitalsLabel: 'Require checking Pulse / Blood Pressure prior to dose',
    medSearchPlaceholder: 'Search medication, patient name, room...',
    medAdministerModalTitle: 'Confirm Medication Administration & Sign-Off',
    medHoldModalTitle: 'Record Clinical Hold on Medication Dose',
    medPulseBeforeDose: 'Pre-dose Pulse (BPM):',
    medBPBeforeDose: 'Pre-dose Blood Pressure (mmHg):',
    medAdministerNotes: 'Clinical notes / Patient response post-dose:',
    medHoldReason: 'Clinical reason for holding (e.g. Bradycardia < 50 bpm, awaiting labs):',
    medFilterAll: 'All Statuses',
    medFilterScheduled: 'Pending / Due',
    medFilterAdministered: 'Completed',
    medFilterHeld: 'Held',
    medTotalDoses: 'Total Scheduled Doses',
    medCompletedDoses: 'Administered',
    medPendingDoses: 'Pending / Due',
    medSyncedCount: 'Synced to Google Calendar',

    // Footer
    footerSystemName: 'Hospital Emergency Telemetry & Clinical Escalation (Stat-Alert)',
    footerVersion: 'ICU Telemetry v2.4',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (typeof translations)['vi'];
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'vi',
  setLanguage: () => {},
  t: translations.vi,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('stat_alert_lang');
      if (saved === 'en' || saved === 'vi') return saved;
    }
    return 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('stat_alert_lang', lang);
    }
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
